# Use a modern Ubuntu base
FROM i-rw-spack-stack:latest

# Set spack-stack location
ENV SPACK_STACK_ROOT=/opt/spack-stack
ENV SPACK_ROOT=$SPACK_STACK_ROOT/spack

# Create new spack environment called regrid-wrapper and install esmf
RUN /bin/bash -c "source $SPACK_STACK_ROOT/setup.sh && \
    spack env create regrid-wrapper && \
    spack mirror add binary_mirror  https://binaries.spack.io/develop && \
    spack buildcache keys --install --trust && \
    spack -e regrid-wrapper add esmf+python@8.9.1 py-netcdf4 py-pydantic py-pytest py-xarray prod-util nco && \
    spack -e regrid-wrapper install" && \
    echo "spack env activate regrid-wrapper" >> /etc/bash.bashrc

# Set the default command
CMD ["/bin/bash"]
