name: regrid-wrapper-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - esmpy=8.4.*=mpi_mpich*
  - xarray
  - mpi4py=3.1.*
  - numpy=1.23.*
  - netcdf4=1.6.*=mpi_mpich*
  - uxarray
  - nco
  - mypy
  - black
  - pytest
  - nccmp
  - pydantic
